# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_0Lp0rbBOtjzgXlWWClIOBJAkY0QrCX
"""

nome_missao = "Aleph-01"
nome_equipe = "01"

dados_missao = [
 [24, 92, 88, 96, 90],
 [27, 80, 72, 94, 85],
 [31, 65, 58, 91, 70],
 [36, 42, 38, 87, 55],
 [39, 28, 19, 78, 35],
 [34, 55, 32, 82, 50]
]
areas_monitoradas = [
 "Temperatura interna",
 "Comunicação com a base",
 "Sistema de energia",
 "Suporte de oxigênio",
 "Estabilidade operacional"
]
def analisar_temperatura(temp):
    if temp < 18:
        return "ATENÇÃO", 1, "Temperatura baixa"
    elif 18 <= temp <= 30:
        return "NORMAL", 0, "Temperatura estável"
    elif 31 <= temp <= 35:
        return "ATENCÃO", 1, "Temperatura elevada"
    else:
        return "CRÍTICO", 2, "Risco de superaquecimento"
# ------------------------------------------------------------------------
def analisar_comunicacao(comunicacao):
    if comunicacao < 30:
        return "CRÍTICO", 2, "Comunicação em nível crítico"
    elif 30 <= comunicacao <= 59:
        return "ATENÇÃO", 1, "Comunicação instável"
    else:
        return "NORMAL", 0, "Comunicação estável"
# ------------------------------------------------------------------------
def analisar_bateria(bateria):
    if bateria < 20:
        return "CRÍTICO", 2, "Bateria em nível crítico"
    elif 20 <= bateria <= 49:
        return "ATENÇÃO", 1, "Bateria abaixo do recomendado"
    else:
        return "NORMAL", 0, "Energia estável"
# ------------------------------------------------------------------------
def analisar_oxigenio(oxigenio):
    if oxigenio < 80:
        return "CRÍTICO", 2, "Oxigênio em nível crítico"
    elif 80 <= oxigenio <= 89:
        return "ATENÇÃO", 1, "Oxigênio abaixo do ideal"
    else:
        return "NORMAL", 0, "Oxigênio adequado"
# ------------------------------------------------------------------------
def analisar_estabilidade(estabilidade):
    if estabilidade < 40:
        return "CRÍTICO", 2, "Estabilidade operacional crítica"
    elif 40 <= estabilidade <= 69:
        return "ATENÇÃO", 1, "Estabilidade operacional reduzida"
    else:
        return "NORMAL", 0, "Estabilidade operacional adequada"
# ------------------------------------------------------------------------
def classificar_ciclo(total_pontos):
    if 0 <= total_pontos <= 2:
        return "MISSÃO ESTÁVEL"
    elif 3 <= total_pontos <= 5:
        return "MISSÃO EM ATENÇÃO"
    else:
        return "MISSÃO CRÍTICA"
# ------------------------------------------------------------------------
def analisar_tendencia(total_pontos_ciclo):
    if total_pontos_ciclo[0] < total_pontos_ciclo[-1]:
        return "A missão apresentou tendência de piora."
    elif total_pontos_ciclo[0] > total_pontos_ciclo[-1]:
        return "A missão apresentou tendência de melhora."
    else:
        return "A missão permaneceu estável em relação ao início."
# ------------------------------------------------------------------------
def identificar_area_mais_afetada(pontos_areas, areas):
    maior_pontuacao = -1
    indice_maior = 0
    for i in range(len(pontos_areas)):
        if pontos_areas[i] > maior_pontuacao:
            maior_pontuacao = pontos_areas[i]
            indice_maior = i
    return areas[indice_maior]
# ------------------------------------------------------------------------
def gerar_recomendacao(total_pontos, status_temp):
    if total_pontos == 0:
        return "Manter operação normal e continuar monitoramento."
    elif total_pontos == 1 or total_pontos == 2 or total_pontos == 6:
        if status_temp in ["ATENÇÃO", "CRÍTICO"]:
            return "Verificar controle térmico da missão."
    elif total_pontos == 10:
        return "Ativar modo de segurança e priorizar suporte à vida, energia e comunicação."
    elif 3 <= total_pontos <= 5:
        return "Monitorar sistemas em atenção e preparar plano de contingência."

    return
# ------------------------------------------------------------------------
def gerar_relatorio_final(dados_missao):

    total_pontos_ciclo = []
    qntd_ciclos = len(dados_missao)

    # Acumulos criticos
    acumulo_temp = 0
    acumulo_comunicacao = 0
    acumulo_bateria = 0
    acumulo_oxigenio = 0
    acumulo_estabilidade = 0

    # Acumulos soma
    soma_temp = 0
    soma_comunicacao = 0
    soma_bateria = 0
    soma_oxigenio = 0
    soma_estabilidade = 0

    print('=' * 65)
    print("MISSION CONTROL AI")
    print('=' * 65)
    print(f"Missão: {nome_missao}")
    print(f"Equipe: {nome_equipe}")
    print(f"Quantidade de ciclos analizados: {len(dados_missao)}")
    print('=' * 65)
    print()


    for i, linha in enumerate(dados_missao, start=1):

        temp = linha[0]
        comunicacao = linha[1]
        bateria = linha[2]
        oxigenio = linha[3]
        estabilidade = linha[4]

        status_temp, nivel_temp, msg_temp = analisar_temperatura(temp)
        status_comunicacao, nivel_comunicacao, msg_comunicacao = analisar_comunicacao(comunicacao)
        status_bateria, nivel_bateria, msg_bateria = analisar_bateria(bateria)
        status_oxigenio, nivel_oxigenio, msg_oxigenio = analisar_oxigenio(oxigenio)
        status_estabilidade, nivel_estabilidade, msg_estabilidade = analisar_estabilidade(estabilidade)

        # Soma das pontuações
        total_pontos = nivel_temp + nivel_comunicacao + nivel_bateria + nivel_oxigenio + nivel_estabilidade



        # Classificação da missão de acordo com a função
        classificacao_missao = classificar_ciclo(total_pontos)

        print(f"CICLO {i}")
        print('-' * 65)
        print(f"Temperatura:  {temp}° | {status_temp:<7} | {msg_temp}")
        print(f"Comunicação:  {comunicacao}% | {status_comunicacao:<7} | {msg_comunicacao}")
        print(f"Bateria:      {bateria}% | {status_bateria:<7} | {msg_bateria}")
        print(f"Oxigênio:     {oxigenio}% | {status_oxigenio:<7} | {msg_oxigenio}")
        print(f"Estabilidade: {estabilidade}% | {status_estabilidade:<7} | {msg_estabilidade}\n")
        print(f"Pontuação de risco do ciclo: {total_pontos} pontos")
        print(f"Classificação do ciclo: {classificacao_missao}")
        print(f"Recomendação: {gerar_recomendacao(total_pontos, status_temp)}\n")

        # Armazena o total de pontos do ciclo na lista fora do loop
        total_pontos_ciclo.append(total_pontos)

        # Acumulos crit
        acumulo_temp += nivel_temp
        acumulo_comunicacao += nivel_comunicacao
        acumulo_bateria += nivel_bateria
        acumulo_oxigenio += nivel_oxigenio
        acumulo_estabilidade += nivel_estabilidade

        # Acumulos soma
        soma_temp += temp
        soma_comunicacao += comunicacao
        soma_bateria += bateria
        soma_oxigenio += oxigenio
        soma_estabilidade += estabilidade

    media_temp = soma_temp / qntd_ciclos
    media_comunicacao = soma_comunicacao / qntd_ciclos
    media_bateria = soma_bateria / qntd_ciclos
    media_oxigenio = soma_oxigenio / qntd_ciclos
    media_estabilidade = soma_estabilidade / qntd_ciclos

    if classificar_ciclo == "MISSÃO ESTÁVEL":
        conclusao = "A missão permaneceu estável na maior parte do tempo. Os sistemas operaram dentro dos parâmetros normais."
    elif classificar_ciclo == "MISSÃO EM ATENÇÃO":
        conclusao = ("A missão apresentou instabilidade relevante durante a operação. Apesar\n"
                     "da tentativa de recuperação no último ciclo, ainda existem sistemas em\n"
                     "atenção e a equipe deve manter o plano de contingência ativo.")
    else:
        conclusao = "A missão atingiu níveis severos de falhas concomitantes. Ativar protocolo máximo de evacuação/segurança."

    print('=' * 65)
    print("RELATÓRIO FINAL DA MISSÃO")
    print('=' * 65)
    print(f"Missão: {nome_missao}")
    print(f"Equipe: {nome_equipe}")
    print(f"\nQuantidade de ciclos analizados: {len(dados_missao)}")

    print(f"\nMédia de temperatura: {media_temp:.2f} °C")
    print(f"Média de comunicação: {media_comunicacao:.2f} %")
    print(f"Média de baterio: {media_bateria:.2f} %")
    print(f"Média de oxigênio: {media_oxigenio:.2f} %")
    print(f"Média de estabilidade: {media_estabilidade:.2f} %")


    ciclo_mais_critico = total_pontos_ciclo.index(total_pontos)
    print(f"\nCiclo mais crítico: Ciclo {ciclo_mais_critico}")
    maior_pontuacao = max(total_pontos_ciclo)
    print(f"Maior pontuação de risco: {maior_pontuacao}")
    risco_medio = sum(total_pontos_ciclo) / len(total_pontos_ciclo)
    print(f"Risco médio da missão: {risco_medio:.2f}")
    quantidade_criticos = 0
    for pontos in total_pontos_ciclo:
        if pontos >= 6:
            quantidade_criticos += 1
    print(f"Quantidade de ciclos críticos: {quantidade_criticos}")


    print("\nTendência da missão:")
    print(analisar_tendencia(total_pontos_ciclo))

    print("\nPontuação acumulada por área:")
    print(f"Temperatura interna: {acumulo_temp} pontos")
    print(f"Comunicação com a base: {acumulo_comunicacao} pontos")
    print(f"Sistema de energia: {acumulo_bateria} pontos")
    print(f"Suporte de oxigênio: {acumulo_oxigenio} pontos")
    print(f"Estabilidade operacional: {acumulo_estabilidade} pontos")

    pontos_areas = [acumulo_temp, acumulo_comunicacao, acumulo_bateria, acumulo_oxigenio, acumulo_estabilidade]
    area_mais_afetada = identificar_area_mais_afetada(pontos_areas, areas_monitoradas)

    print(f"\nÁrea mais afetada:\n{area_mais_afetada}")
    print(f"\nClassificação do ciclo: {classificacao_missao}")
    print(f"\nConclusão:\n{conclusao}")
    return

gerar_relatorio_final(dados_missao)
